---
- name: Set up apache2
  hosts: n1
  become: yes
  

  tasks:
  - name: install apache2
    yum:
      name: apache2
      state: present
    

      
  - name: Start apache2
    service:
      name: apache2
      state: started
      
      
  - name: Enable apache2
    service:
      name: apache2
      enabled: true
      
      



...
