---
- name: Set up apache2
  hosts: n2
  become: yes
  

  tasks:
  - name: Install apache2
    apt:
     name: apache2
     state: presen
    

      
  - name: Start apache2
    service:
      name: apache2
      state: started
      
      
  - name: Enable apache2
    service:
      name: apache2
      enabled: true
...
