---
- name: Changing the port dynamically
  hosts: n1
  become: yes
  vars:
    custom_port: 9090
    
  
  tasks:
  - name: changing the port number
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
  - name: restarting httpd
    service:
     name: httpd
     state: restart
...