---
- name: static web page
  hosts: all
  become: yes
  vars:
    user_name: Gowthamboppa


  tasks:
  - name: coping file to all
    template:
      src: info.j2
      dest: /var/www/html/dynamic.html
      
    
...
