---
- name: Cretaing dyamic page
  hosts: all
  become: yes
  var: 
    user_name: gowtham
  

  tasks:
  - name: dynamic username
    template:
      src: info.j2
      dest: /var/www/html/dynamic.html

...