---
- name: Set up httpd
  hosts: n1
  become: yes 
  

  tasks:
  - name: Install git
    yum:
      name: git
      state: present
      

      
  - name: cloning
    git:
      dest: /var/www/html
      repo: https://github.com/ravi2krishna/ecomm.git
      become: yes

...
