---
- name: Set up httpd
  hosts: n1
  become: yes

  tasks:
  - name: install
    yum:
      name: httpd
      state: present
      
  - name: Start httpd
    service:
      name: httpd
      state: started
      
  - name: Enable Httpd
    service:
      name: httpd
      enabled: true
      



...
