---
- name: Set up httpd
  hosts: n1

  tasks:
  - name: Install Httpd
    yum:
      name: httpd
      state: present
      become: yes
  - name: Start Httpd
    service:
      name: httpd
      state: started
      become: yes
  - name: Enable Httpd
    service:
      name: httpd
      enabled: true
      become: yes



...
