---
- name: file copying
  file:
    name: gowtham
    state: directory



- name: dynamic username
  template:
    src: info.j2
    dest: /var/www/html/dynamic.html

- name: changing the port number
  template:
    src: httpd.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restarting httpd
...


